# Generated by Django 3.2.12 on 2022-03-24 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('hobbies', models.CharField(max_length=50)),
                ('national_id_type', models.CharField(choices=[('Ghana Card', 'Ghana Card'), ('Drivers License', 'Driver License'), ('Passport', 'Passport'), ('voter ID', 'Voter ID'), ('other', 'Other')], max_length=50)),
                ('national_id', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Details',
                'db_table': 'Customer Details',
            },
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='CustomerReservations',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.customerdetails')),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.facilities')),
            ],
            options={
                'verbose_name_plural': 'Customer Reservations',
                'db_table': 'Customer Reservations',
            },
        ),
        migrations.CreateModel(
            name='CustomerPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.customerdetails')),
            ],
            options={
                'verbose_name_plural': 'Customer Payments',
                'db_table': 'Customer Payments',
            },
        ),
        migrations.CreateModel(
            name='CustomerFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.customerdetails')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.facilities')),
            ],
            options={
                'verbose_name_plural': 'Customer Facility',
                'db_table': 'Customer Facility',
            },
        ),
    ]
