# Generated by Django 3.2.12 on 2022-03-23 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilities',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='date_of_birth',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='national_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='registration_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerfacility',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.customerdetails'),
        ),
        migrations.AlterField(
            model_name='customerfacility',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.facilities'),
        ),
    ]
